config/routes.rb
Rails.application.routes.draw do

  resources :challenges, only: [:index] do
    resources :timeslots, except: [:edit, :update] do
      post 'cancel', on: :member
      post 'accept', on: :member
    end
  end

  get '/dashboard', to: "authentication#dashboard"
  get '/logout', to: "authentication#logout"
  post '/login', to: "authentication#login"
  match "/auth/github/callback" => "authentication#login", :via => [:get, :post]
  post '/timezone', to: "authentication#timezone"
  post '/slack_name', to: "authentication#slack_name"

  root to: 'authentication#index'
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController

  skip_before_action :require_login, only: [:index, :login]

  def index
    @page_title = "Login"
    redirect_to challenges_path if current_student
  end

  def login
    omniauth_hash = request.env["omniauth.auth"]
    student = Student.find_by(
      username: omniauth_hash["info"]["nickname"]
    ) || Student.create_with_omniauth(omniauth_hash)
    session[:student_id] = student.id
    redirect_to challenges_path, :notice => "Signed in!"
  end

  def logout
    session[:student_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end

  def dashboard
    @page_title = "Dashboard"
    @student = current_student
    @initiated_timeslots = @student.initiated_timeslots
    @unpaired_timeslots = Timeslot.where(initiator: @student, acceptor: nil)
    @paired_timeslots = Timeslot.where(initiator: @student, acceptor: !nil) + @student.accepted_timeslots
  end

  def timezone
    @student = current_student
    if request.xhr?

      @student.time_zone = params[:time_zone]
    else
      @student.time_zone = params[:timezone][:time_zone]
    end
    @student.save
  end

  def slack_name
    @student = current_student
    if request.xhr?
      @student.slack_name = params[:slack_name]
    else
      @student.slack_name = params[:slack_name][:slack_name]
    end
    @student.save
  end

end

app/helpers/authentication_helper.rb
module AuthenticationHelper

end

app/views/authentication/dashboard.html.erb
<h1>Hello, <%= @student.fullname %></h1>
<% if @paired_timeslots.present? %>
  <h2>Your Pairing Sessions</h2>
  <div class="list">
    <table id="paired-list">
        <% @paired_timeslots.each do |timeslot| %>
          <tr class="timeslot">
              <td><%= timeslot.initiator.fullname %> is pairing with <%= timeslot.acceptor.fullname %> at <%= timeslot_string(timeslot) %>.</td>
              <td><%= button_to 'Cancel',
                cancel_challenge_timeslot_path(timeslot.challenge_id, timeslot.id),
                method: :post,
                data: { confirm: 'Are you sure?' },
                class: "btn btn-danger" %></td>
          </tr>
        <% end %>
    </table>
  </div>
<% end %>

<% if @unpaired_timeslots.present?%>
  <h2>You are available to pair at:</h2>
  <div class="list">
    <table id="unpaired-list">
        <% @unpaired_timeslots.each do |timeslot| %>
          <tr class="timeslot">
            <td><%= timeslot_string(timeslot) %></td>
            <td><%= button_to 'Delete',
              challenge_timeslot_path(timeslot.challenge_id, timeslot.id),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: "btn btn-warning" %></td>
          </tr>
        <% end %>
    </table>
  </div>
<% end %>


<div class="slack-form">
  <% unless current_student.slack_name.present? %>
    <%= form_for :slack_name, :url => slack_name_path do |f| %>
      <%= f.label :slack_name %>
      <div class="row" id="timezone-form">
        <div class="col-lg-8">
        <%= f.text_field :slack_name, class: "form-control form-control-sm" %>
        </div>
        <div class="col-lg-4">
        <%= f.submit "Update", method: "post", class: "btn btn-primary" %>
        </div>
    <% end %>

  <% else %>
    <h3>Your Slack Username: <span id="slack_name"><%= current_student.slack_name %></span>.
    <button id="slack-edit-button" class= "btn btn-primary">Click to change</button></h3>
    <%= form_for :slack_name, :url => slack_name_path, method: "post", html: { id: "update-slack", class: "hidden" } do |f| %>
      <%= f.label :slack_name %>
      <%= f.text_field :slack_name %>
      <%= f.submit "Update Slack username", class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/authentication/index.html.erb
<main>
  <h1 id="landing-logo">pair<i>Booked</i></h1>
  <a class="btn btn-success" id="login-button" href="/auth/github" role="button">Login</a>
</main>