config/routes.rb
Rails.application.routes.draw do

  resources :challenges, only: [:index] do
    resources :timeslots, except: [:edit, :update] do
      post 'cancel', on: :member
      post 'accept', on: :member
    end
  end

  get '/dashboard', to: "authentication#dashboard"
  get '/logout', to: "authentication#logout"
  post '/login', to: "authentication#login"
  match "/auth/github/callback" => "authentication#login", :via => [:get, :post]
  post '/timezone', to: "authentication#timezone"
  post '/slack_name', to: "authentication#slack_name"

  root to: 'authentication#index'
end

app/models/timeslot.rb
class Timeslot < ApplicationRecord
  belongs_to :challenge
  belongs_to :initiator, class_name: :Student, foreign_key: :initiator_id
  belongs_to :acceptor, class_name: :Student, foreign_key: :acceptor_id, required: false
  validates_presence_of :initiator_id, :challenge_id, :start_at, :end_at
  validate :must_start_before_end, :acceptor_must_be_diff_person
  scope :future, -> { where("start_at > ?", Time.now) }
  scope :not_mine, -> (student) { where("initiator_id != ?", student.id) }
  scope :soon, -> { where("start_at < ?", Time.now + 2.hours)}
  scope :not_soon, -> { where("start_at > ?", Time.now + 2.hours)}
  scope :no_pair, -> { where("acceptor_id IS NULL")}
  default_scope { order(start_at: :asc) }

  def self.clean_up
    self.where( start_at:(Time.now.midnight - 30.days)..Time.now.midnight).each do |timeslot|
      timeslot.destroy
    end
  end

  def time_zone
    self.initiator.time_zone
  end

  def must_start_before_end
    if start_at && end_at
      if start_at.to_date < DateTime.now.to_date
        errors.add(:start_date, "must be after #{DateTime.now.to_date}.")
      elsif (start_at.to_date == DateTime.now.to_date) && (start_at.strftime('%F%H:%M') < DateTime.now.strftime('%F%H:%M'))
        current_time = DateTime.now.strftime("%I:%M %p")
        errors.add(:start_time, "must be after #{current_time}.")
      elsif start_at.to_time > end_at.to_time
        errors.add(:start_time, "must be after end time.")
      end
    end
  end

  def acceptor_must_be_diff_person
    if self.acceptor == self.initiator
      errors.add(:acceptor, "cannot accept own timeslot")
    end
  end
end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  include TimeslotsHelper
  include Mail
  def index
    @challenge = Challenge.find_by_id(params[:challenge_id])
    if @challenge
      @page_title = "#{@challenge.name}"
      @not_soon_timeslots = @challenge.get_not_soon_timeslots(current_student)
      @soon_timeslots = @challenge.get_soon_timeslots(current_student)
    else
      redirect_to challenges_path
    end
  end

  def accept
    @timeslot = Timeslot.find_by_id(params[:id])
    @timeslot.acceptor = current_student
    if @timeslot.save
      empty_timeslots = Timeslot.where(initiator_id: @timeslot.initiator_id, challenge_id: @timeslot.challenge_id, acceptor_id: nil)
      empty_timeslots.each do |timeslot|
        timeslot.destroy
      end

      overlap_timeslots = Timeslot.where(initiator_id: @timeslot.initiator_id, start_at: @timeslot.start_at, acceptor_id: nil)
      overlap_timeslots.each do |timeslot|
        timeslot.destroy
      end
      send_confirmation(@timeslot)
    end
    redirect_to challenge_timeslot_path(@timeslot.challenge_id, @timeslot)
  end

  def show
    @timeslot = Timeslot.find_by_id(params[:id])
    @page_title = @timeslot.challenge.name + " timeslots"
  end

  def destroy
    Timeslot.destroy(params[:id])
    redirect_to dashboard_path
  end

  def new
    @challenge = Challenge.find_by_id(params[:challenge_id])
    @page_title = "Input availability for #{@challenge.name}"
  end

  def create
    sanitized_params = timeslots_params
    if sanitized_params[:start_date] != "" && sanitized_params[:start_time] != "" && sanitized_params[:end_time] != ""
      convert_to_datetime(sanitized_params)
    end
    @challenge = Challenge.find_by_id(params[:challenge_id])

    if sanitized_params[:end_at] <= sanitized_params[:start_at]
      @errors = ["Start time must before end time."]
      render action: "new"
    elsif sanitized_params[:start_at] <= DateTime.now

      @errors = ["Start time must after the current time."]
      render action: "new"
    else
      create_timeslots(sanitized_params[:start_at],sanitized_params[:end_at],current_student.id, @challenge)
      redirect_to "/challenges/#{params[:challenge_id]}/timeslots", notice: 'Tweet was successfully created.'
    end
  end

  def cancel
    timeslot = Timeslot.find(params[:id])
    send_cancellation(timeslot)
    timeslot.destroy
    redirect_to dashboard_path
  end

end

app/helpers/timeslots_helper.rb
module TimeslotsHelper

  def show_time_options
    [
      ['12:00AM', "00:00"],
      ['1:00AM', "01:00"],
      ['2:00AM', "02:00"],
      ['3:00AM', "03:00"],
      ['4:00AM', "04:00"],
      ['5:00AM', "05:00"],
      ['6:00AM', "06:00"],
      ['7:00AM', "07:00"],
      ['8:00AM', "08:00"],
      ['9:00AM', "09:00"],
      ['10:00AM', "10:00"],
      ['11:00AM', "11:00"],
      ['12:00PM', "12:00"],
      ['1:00PM', "13:00"],
      ['2:00PM', "14:00"],
      ['3:00PM', "15:00"],
      ['4:00PM', "16:00"],
      ['5:00PM', "17:00"],
      ['6:00PM', "18:00"],
      ['7:00PM', "19:00"],
      ['8:00PM', "20:00"],
      ['9:00PM', "21:00"],
      ['10:00PM', "22:00"],
      ['11:00PM', "23:00"]
    ]
  end

  def timeslot_string(timeslot)
    timeslot.start_at.in_time_zone(current_time_zone).strftime("%B %d %Y from %l:%M %P") + " to " + timeslot.end_at.in_time_zone(current_time_zone).strftime("%l:%M %P")
  end

  def timeslots_params
    params.require(:timeslots).permit( :start_date, :start_time, :end_time)
  end

  def convert_to_datetime(params)
    start_datetime = params[:start_date] + " " + params[:start_time]
    params[:start_at] = start_datetime.in_time_zone(zone = current_time_zone)
    end_datetime = params[:start_date] + " " + params[:end_time]
    params[:end_at] = end_datetime.in_time_zone(zone = current_time_zone)
  end

  def create_timeslots(start_at, end_at, initiator_id, challenge)
    temp_start_at = start_at + 1.hour
    if duration_greater_than_hour(start_at, end_at)
      create_timeslot(start_at, temp_start_at, initiator_id, challenge)
      create_timeslots(temp_start_at, end_at, initiator_id, challenge)
    else
      create_timeslot(start_at, temp_start_at, initiator_id, challenge)
    end
  end

  def create_timeslot(start_at, end_at, initiator_id, challenge)
    timeslot = challenge.timeslots.new(
      start_at:     start_at,
      end_at:       end_at
      )
    timeslot.initiator_id = initiator_id
    timeslot.save
  end

  def duration_greater_than_hour(start_at, end_at)
    (((end_at.to_time - start_at.to_time) / 3600).round) > 1
  end

  def send_confirmation(timeslot)
    controller = self
    mail = Mail.new do
      from    'bobolinkpairbook@gmail.com'
      subject   "pairBook #{timeslot.challenge.name}"
      delivery_method :sendmail

      html_part do
        content_type 'text/html; charset=UTF-8'
        body controller.render_to_string(
          :locals => {:@timeslot => timeslot},
          :template => :'timeslots/show.html'
        )
      end
    end

    [timeslot.initiator.email, timeslot.acceptor.email].each do |email|
      mail[:to] = email
      mail.deliver
    end
  end

  def send_cancellation(timeslot)
    controller = self
    mail = Mail.new do
      from    'bobolinkpairbook@gmail.com'
      subject   "CANCELLED pairBook #{timeslot.challenge.name}"
      delivery_method :sendmail

      text_part do
        body "Your pairing on #{controller.timeslot_string(timeslot)} was cancelled. Please re-input your availability for this challenge."
      end
    end

    [timeslot.initiator.email, timeslot.acceptor.email].each do |email|
      mail[:to] = email
      mail.deliver
    end
  end
end

app/views/timeslots/index.html.erb
<div id="timeslot-index-header" class="row">
  <div class="col-lg-10">
    <div class="col-lg-8 col-md-10 col-sm-10">
      <h1><%= @challenge.name %></h1>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2">
    <a class="btn btn-success" href='/challenges/<%= @challenge.id %>/timeslots/new'><span class="glyphicon glyphicon-plus"></span> Create</a>
    </div>
  </div>
<!--   <div class="col-lg-1">
    <a class="btn btn-success" href='/challenges/<%= @challenge.id %>/timeslots/new'><span class="glyphicon glyphicon-plus"></span> Create</a>
  </div> -->
</div>
<br>
<br>
<div>
  <ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#Monday" aria-controls="Monday" role="tab" data-toggle="tab">Monday</a></li>
    <li role="presentation"><a href="#Tuesday" aria-controls="Tuesday" role="tab" data-toggle="tab">Tuesday</a></li>
    <li role="presentation"><a href="#Wednesday" aria-controls="Wednesday" role="tab" data-toggle="tab">Wednesday</a></li>
    <li role="presentation"><a href="#Thursday" aria-controls="Thursday" role="tab" data-toggle="tab">Thursday</a></li>
    <li role="presentation"><a href="#Friday" aria-controls="Friday" role="tab" data-toggle="tab">Friday</a></li>
    <li role="presentation"><a href="#Saturday" aria-controls="Saturday" role="tab" data-toggle="tab">Saturday</a></li>
    <li role="presentation"><a href="#Sunday" aria-controls="Sunday" role="tab" data-toggle="tab">Sunday</a></li>
  </ul>

  <div class="tab-content">

    <div role="tabpanel" class="tab-pane active" id="Monday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Monday] != nil %>
          <% @soon_timeslots[:Monday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
              </li>
          <% end %>
        <% end %>
        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Monday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
              </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="Tuesday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Tuesday] != nil %>
          <% @soon_timeslots[:Tuesday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
              </li>
          <% end %>
        <% end %>
        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Tuesday].each do |timeslot| %>
            <li class="timeslot">
              <%= timeslot_string(timeslot)%>
              <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="Wednesday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Wednesday] != nil %>
          <% @soon_timeslots[:Wednesday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
              </li>
          <% end %>
        <% end %>

        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Wednesday].each do |timeslot| %>
            <li class="timeslot">
              <%= timeslot_string(timeslot)%>
              <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="Thursday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Thursday] != nil %>
          <% @soon_timeslots[:Thursday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
                <!-- <span class="soon-warning">! Starts soon</span> -->
              </li>
          <% end %>
        <% end %>

        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Thursday].each do |timeslot| %>
            <li class="timeslot">
              <%= timeslot_string(timeslot)%>
              <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="Friday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Friday] != nil %>
          <% @soon_timeslots[:Friday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
              </li>
          <% end %>
        <% end %>

        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Friday].each do |timeslot| %>
            <li class="timeslot">
              <%= timeslot_string(timeslot)%>
              <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="Saturday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Saturday] != nil %>
          <% @soon_timeslots[:Saturday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
              </li>
          <% end %>
        <% end %>

        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Saturday].each do |timeslot| %>
            <li class="timeslot">
              <%= timeslot_string(timeslot)%>
              <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>

    <div role="tabpanel" class="tab-pane" id="Sunday">
      <ul class="timeslots-list">
        <% if @soon_timeslots[:Sunday] != nil %>
          <% @soon_timeslots[:Sunday].each do |timeslot| %>
              <li class="timeslot">
                <%= timeslot_string(timeslot)%>
                <a class="btn btn-warning btn-sm pull-right soon" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join <i class="glyphicon glyphicon-alert"></i></a>
              </li>
          <% end %>
        <% end %>

        <% if @not_soon_timeslots != nil %>
          <% @not_soon_timeslots[:Sunday].each do |timeslot| %>
            <li class="timeslot">
              <%= timeslot_string(timeslot)%>
              <a class="btn btn-primary btn-sm pull-right" href="/challenges/<%=timeslot.challenge_id%>/timeslots/<%= timeslot.id %>">Join</a>
            </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>

</div>

app/views/timeslots/new.html.erb
<div class="availability-form">
  <h1>Input Your Availability</h1>
  <p>We will create pairing session times based on when you are available.</p>
  <%= form_for :timeslots, :url => challenge_timeslots_path do |f| %>
    <div class="form-group">


      <div class="form-group row">
        <%= f.label :start_date, :class => "col-xs-2 col-form-label" %>
        <div class="col-xs-10 col-sm-4 col-md-3 col-lg-2">
          <%= f.datetime_local_field :start_date, class: "form-control", :value => @timeslot.try(:start_date), :type =>"date", :id => "timeslot-date-input", :required => true %>
        </div>
      </div>

      <div class="form-group row">
        <%= f.label :start_time, :class => "col-xs-2 col-form-label" %>
        <div class="col-xs-10 col-sm-4 col-md-3 col-lg-2">
          <%= f.select :start_time,show_time_options, {}, class: "form-control form-control-sm", :id => "timeslot-time-start-input", :required => true %>

        </div>
      </div>

      <div class="form-group row">
        <%= f.label :end_time, :class => "col-xs-2 col-form-label" %>
        <div class="col-xs-10 col-sm-4 col-md-3 col-lg-2">
          <%= f.select :end_time,show_time_options, {}, class: "form-control form-control-sm", :id => "timeslot-time-end-input", :required => true %>
        </div>
      </div>
    </div>

  <% if @errors %>
    <div class="errors" id="timeslot-errors">
      <ul>
        <% @errors.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/timeslots/show.html.erb
<h1>Pairing Booking for <%= @timeslot.challenge.name %></h1>

<main>
  <%if @timeslot.acceptor.blank? %>
    <p><%= @timeslot.initiator.fullname %> is looking for a pair
  <% else %>
    <p><%=@timeslot.initiator.fullname%> will be pairing with <%= @timeslot.acceptor.fullname%>
  <% end %>
  for this assignment at <%= @timeslot.start_at.strftime("%l:%M %P on %A, %B %e") %>.</p>
  <% unless @timeslot.acceptor.blank? %>
    <p><%= @timeslot.acceptor.fullname %> can be contacted at: <%= @timeslot.acceptor.email %><% if @timeslot.acceptor.slack_name %>, or on Slack at <%= @timeslot.acceptor.slack_name %><% end %>.</p>
  <% end %>
  <p><%= @timeslot.initiator.fullname %> can be contacted at: <%= @timeslot.initiator.email %><% if @timeslot.initiator.slack_name %>, or on Slack at <%= @timeslot.initiator.slack_name %><% end %>.</p>
  <% if(@timeslot.acceptor.blank? && @timeslot.initiator != current_student) %>
    <%= form_for(:accept_timeslot, url: accept_challenge_timeslot_path(@timeslot.challenge, @timeslot)) do |f| %>
      <%= f.submit "Book Timeslot", class: "btn btn-success", id: "book-button" %>
    <% end %>

  <% end %>
</main>