config/routes.rb
Rails.application.routes.draw do

  resources :challenges, only: [:index] do
    resources :timeslots, except: [:edit, :update] do
      post 'cancel', on: :member
      post 'accept', on: :member
    end
  end

  get '/dashboard', to: "authentication#dashboard"
  get '/logout', to: "authentication#logout"
  post '/login', to: "authentication#login"
  match "/auth/github/callback" => "authentication#login", :via => [:get, :post]
  post '/timezone', to: "authentication#timezone"
  post '/slack_name', to: "authentication#slack_name"

  root to: 'authentication#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pairBooked <%= @page_title.blank? ? '' : " - #{@page_title}"  %></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-lg-2">
          <nav class="navbar navbar-default navbar-fixed-side">
            <!-- normal collapsible navbar markup -->
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <div>
                  <%= image_tag "logo.png", :class =>"logo" %>
                </div>
                <div id="navbar-brand-container">
                  <a class="navbar-brand" id="brand" href="/challenges">pair<i>Booked</i></a>
                </div>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="nav-link"><a href="/dashboard">Dashboard</a></li>
                  <li class="nav-link"><a href="/challenges">Challenges</a></li>
                  <% if current_student.present?%>
                    <li class="nav-link"><a href="/logout">Log Out</a></li>
                    <li class="nav-form">
                      <%= form_for :timezone, :url => timezone_path do |f| %>
                        <div class="row" id="timezone-form">
                          <div class="col-lg-12">
                          <%= f.time_zone_select :time_zone, ActiveSupport::TimeZone.us_zones, { :default => current_student.time_zone }, class: "form-control form-control-sm" %>
                          <%= f.submit "Update", class: "btn btn-primary", id: "time-zone-update-button"%>
                          </div>
                        </div>
                      <% end %>
                    </li>
                  <%end%>
                </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
        </div>
        <div class="col-sm-9 col-lg-10">
          <!-- page content -->
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>